[profile.default]
src = "src"
out = "out"
libs = ["lib","dependencies"]

# remappings = ["@openzeppelin/contracts/=dependencies/@openzeppelin-contracts-5.0.2/src/
# ",]


[dependencies]
forge-std = { version = "1.9.2", url = "https://soldeer-revisions.s3.amazonaws.com/forge-std/1_9_2_06-08-2024_17:31:25_forge-std-1.9.2.zip" }
"@openzeppelin-contracts" = "5.0.2"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
